// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package provider

/* import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccABXActionResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: `

variable "test_project_id" {
	description = "Project where to generate test resources."
  type        = string
}

resource "aria_abx_action" "test" {
  name         = "ARIA_PROVIDER_TEST_ACTION"
  description  = "Temporary action generated by Aria provider's acceptance tests."
  runtime_name = "python"
  memory_in_mb = "128"
  entrypoint   = "handler"
  dependencies = []

	project_id = var.test_project_id

  source = <<EOT
from __future__ import annotations

import os


def handler(*args, **kwargs) -> None:
		print('Global symbols :', globals())
		print('Environment variables :', os.environ)
		print('Call Arguments: ', args, kwargs)
EOT

}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_abx_action.test", "id"),
					resource.TestCheckResourceAttrSet("aria_abx_action.test", "org_id"),
					resource.TestCheckResourceAttr("aria_abx_action.test", "name", "ARIA_PROVIDER_TEST_ACTION"),
				),
			},
			// ImportState testing
			/*{
							ResourceName:      "aria_abx_action.test",
							ImportState:       true,
							ImportStateVerify: true,
						},
						// Update and Read testing
						{
							Config: `
			resource "aria_abx_action" "test" {
			  name  = "ARIA_PROVIDER_TEST_CONSTANT"
			  value = "newvalue"
			}`,
							Check: resource.ComposeAggregateTestCheckFunc(
								resource.TestCheckResourceAttrSet("aria_abx_action.test", "id"),
								resource.TestCheckResourceAttrSet("aria_abx_action.test", "org_id"),
								resource.TestCheckResourceAttr("aria_abx_action.test", "name", "ARIA_PROVIDER_TEST_CONSTANT"),
								resource.TestCheckResourceAttr("aria_abx_action.test", "value", "newvalue"),
								resource.TestCheckResourceAttr("aria_abx_action.test", "encrypted", "false"),
							),
						} /
			// Delete testing automatically occurs in TestCase
			// TODO Check https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests/testcase#checkdestroy
		},
	})
}
*/
