// Copyright (c) State of Geneva (Switzerland)
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccCatalogSourceResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: `
resource "aria_orchestrator_category" "root" {
  name      = "TEST_ARIA_PROVIDER"
  type      = "WorkflowCategory"
  parent_id = ""
}

resource "aria_orchestrator_workflow" "test" {
  name        = "Test Workflow for Catalog Source"
  description = "Workflow generated by the acceptance tests of Aria provider."
  category_id = aria_orchestrator_category.root.id
  version     = "0.1.0"

  position = { x = 100, y = 50 }

  restart_mode            = 1 # resume
  resume_from_failed_mode = 0 # default

  attrib        = jsonencode([])
  presentation  = jsonencode({})
  workflow_item = jsonencode([])

  input_parameters  = []
  output_parameters = []

  input_forms = jsonencode([
    {
      layout = {
        pages = []
      }
      schema = {}
    }
  ])
}

resource "aria_catalog_source" "test" {
  name    = "ARIA_PROVIDER_TEST_CATALOG_SOURCE"
  type_id = "com.vmw.vro.workflow"

  config = {
    workflows = [
    	{
	      id          = aria_orchestrator_workflow.test.id
	      name        = aria_orchestrator_workflow.test.name
	      description = aria_orchestrator_workflow.test.description
	      version     = aria_orchestrator_workflow.test.version
	    }
	  ]
  }
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_catalog_source.test", "id"),
					resource.TestCheckResourceAttr("aria_catalog_source.test", "name", "ARIA_PROVIDER_TEST_CATALOG_SOURCE"),
					resource.TestCheckResourceAttr("aria_catalog_source.test", "type_id", "com.vmw.vro.workflow"),
					resource.TestCheckResourceAttr("aria_catalog_source.test", "global", "false"),
					resource.TestCheckResourceAttr("aria_catalog_source.test", "config.source_project_id", ""),
					/*resource.TestCheckResourceAttrPair(
					  	"aria_catalog_source.test", "config.workflows[0].id",
					  	"aria_orchestrator_workflow.test", "id",
					  ),
					  resource.TestCheckResourceAttrPair(
					  	"aria_catalog_source.test", "config.workflows[0].name",
					  	"aria_orchestrator_workflow.test", "name",
					  ),
					  resource.TestCheckResourceAttrPair(
					  	"aria_catalog_source.test", "config.workflows[0].version",
					  	"aria_orchestrator_workflow.test", "version",
					  ),*/
				),
			},

			// ImportState testing
			/* TODO https://github.com/davidfischer-ch/terraform-provider-aria/issues/111
			   {
			     ResourceName:      "aria_catalog_source.test",
			     ImportState:       true,
			     ImportStateVerify: true,
			   }, */
			// Delete testing automatically occurs in TestCase
			// TODO Check https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests/testcase#checkdestroy
		},
	})
}
