// Copyright (c) State of Geneva (Switzerland)
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccOrchestratorActionResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: `

locals {
	script = <<EOT
// Get VRA Host by type
var vrahosts = VraHostManager.findHostsByType("vra-onprem");
for each ( var host in vrahosts ) {
    var vRAHost = host;
    System.warn("vRA Host is : "+vRAHost.vraHost)
    }
return vRAHost;

EOT
}

resource "aria_orchestrator_action" "test" {
  name                 = "ARIA_PROVIDER_TEST_ACTION"
  module               = "aria_provider_tests"
  fqn                  = "aria_provider_tests/ARIA_PROVIDER_TEST_ACTION"
  description          = "Temporary action generated by Aria provider's acceptance tests."
  version              = "1.0.0"
  runtime              = ""
  runtime_memory_limit = 128 * 1024 * 1024
  runtime_timeout      = 30
  script               = local.script
  input_parameters     = []
  output_type          = "VRA:Host"

  lifecycle {
    postcondition {
      condition     = self.script == local.script
      error_message = "Script must be ${local.script}, actual ${self.script}"
    }
  }
}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_orchestrator_action.test", "id"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "name", "ARIA_PROVIDER_TEST_ACTION"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "description", "Temporary action generated by Aria provider's acceptance tests."),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "version", "1.0.0"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "module", "aria_provider_tests"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "runtime", ""),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "runtime_memory_limit", "134217728"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "runtime_timeout", "30"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "output_type", "VRA:Host"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "fqn", "aria_provider_tests/ARIA_PROVIDER_TEST_ACTION"),
				),
			},
			/*// Update and Read testing
			{
				Config: `
variable "test_project_id" {
	description = "Project where to generate test resources."
  type        = string
}

resource "aria_abx_constant" "test" {
	count = 3
  name  = "ARIA_PROVIDER_TEST_ACTION_CONSTANT_${count.index}"
  value = "Some value."
}

resource "aria_abx_sensitive_constant" "test" {
	count = 2
  name  = "ARIA_PROVIDER_TEST_ACTION_SECRET_${count.index}"
  value = "sensitive stuff."
}

locals {
	dependencies = ["requests", "pytoolbox==14.8.2"]

	source = <<EOT
from __future__ import annotations

import os

import requests


def handler(*args, **kwargs) -> None:
		print('Global symbols :', globals())
		print('Environment variables :', os.environ)
		print('Call Arguments: ', args, kwargs)
		print('Requests module: ', requests)
EOT
}

resource "orchestrator_action" "test" {
  name                       = "ARIA_PROVIDER_TEST_ACTION_RENAMED"
  description                = "Temporary action generated by Aria provider's acceptance tests (changed)."
  faas_provider              = "on-prem"
  runtime_name               = "python"
  cpu_shares                 = "128"
  memory_in_mb               = 64
  deployment_timeout_seconds = 300
  entrypoint                 = "handler"
  dependencies               = local.dependencies
  constants                  = []
  secrets                    = []
  source                     = local.source
  project_id                 = var.test_project_id

  lifecycle {
    postcondition {
      condition     = self.dependencies == tolist(local.dependencies)
      error_message = "Dependencies must be [${join(", ", local.dependencies)}], actual [${join(", ", self.dependencies)}]"
    }
    postcondition {
      condition     = length(self.constants) == 0
      error_message = "Constants must be empty, actual [${join(", ", self.constants)}]"
    }
    postcondition {
      condition     = length(self.secrets) == 0
      error_message = "Secrets must be empty, actual [${join(", ", self.secrets)}]"
    }
    postcondition {
      condition     = self.project_id == var.test_project_id
      error_message = "Project ID must be ${var.test_project_id}, actual ${self.project_id}"
    }
    postcondition {
      condition     = self.source == local.source
      error_message = "Source must be ${local.source}, actual ${self.source}"
    }
  }
}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_orchestrator_action.test", "id"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "name", "ARIA_PROVIDER_TEST_ACTION_RENAMED"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "description", "Temporary action generated by Aria provider's acceptance tests (changed)."),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "faas_provider", "on-prem"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "type", "SCRIPT"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "runtime_name", "python"),
					// resource.TestCheckResourceAttrSet("aria_orchestrator_action.test", "runtime_version"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "cpu_shares", "128"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "memory_in_mb", "64"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "timeout_seconds", "600"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "deployment_timeout_seconds", "300"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "entrypoint", "handler"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "shared", "false"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "system", "false"),
					resource.TestCheckResourceAttr("aria_orchestrator_action.test", "async_deployed", "false"),
					resource.TestCheckResourceAttrSet("aria_orchestrator_action.test", "org_id"),
				),
			},*/
			// ImportState testing
			{
				ResourceName:      "aria_orchestrator_action.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}
