// Copyright (c) State of Geneva (Switzerland)
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccOrchestratorConfigurationResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: `
resource "aria_orchestrator_category" "root" {
  name      = "TEST_ARIA_PROVIDER"
  type      = "ConfigurationElementCategory"
  parent_id = ""
}

resource "aria_orchestrator_configuration" "test" {
  name        = "Test Config"
  description = "Config generated by the acceptance tests of Aria provider."
  category_id = aria_orchestrator_category.root.id
  version     = "0.0.0"

  attributes = []

  force_delete = true
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_orchestrator_configuration.test", "id"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "name", "Test Config"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "description", "Config generated by the acceptance tests of Aria provider."),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "version", "0.0.0"),
					resource.TestMatchResourceAttr("aria_orchestrator_configuration.test", "version_id", regexp.MustCompile("[0-9a-f]{40}")),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.#", "0"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "force_delete", "true"),
					resource.TestCheckResourceAttrPair(
						"aria_orchestrator_configuration.test", "category_id",
						"aria_orchestrator_category.root", "id",
					),
				),
			},
			// Update (attributes, description, version) and Read testing
			{
				Config: `
resource "aria_orchestrator_category" "root" {
  name      = "TEST_ARIA_PROVIDER"
  type      = "ConfigurationElementCategory"
  parent_id = ""
}

resource "aria_orchestrator_configuration" "test" {
  name        = "Test Config"
  description = "Config generated by the acceptance tests of Aria provider (updated)."
  category_id = aria_orchestrator_category.root.id
  version     = "0.1.0"

  attributes = [
    {
      name        = "someString"
      description = "Some string value"
      type        = "string"
      value = {
        string = {
          value = "some value"
        }
      }
    },
    {
      name        = "someBoolean"
      description = "Some boolean value"
      type        = "boolean"
      value = {
        boolean = {
          value = true
        }
      }
    }
    /*
		This is not yet well handled (mutated by the platform), we have to find a pattern for this.
    We cannot (?) expose 1-1 the API to make it declarative, we have to tackle this challenge.
    {
      name        = "someSecureString"
      description = "Some secure string value"
      type        = "SecureString"
      value = {
        secure_string = {
          value         = "test"
          is_plain_text = true
        }
      }
    }
    */
  ]

  force_delete = true
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_orchestrator_configuration.test", "id"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "name", "Test Config"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "description", "Config generated by the acceptance tests of Aria provider (updated)."),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "version", "0.1.0"),
					resource.TestMatchResourceAttr("aria_orchestrator_configuration.test", "version_id", regexp.MustCompile("[0-9a-f]{40}")),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.#", "2"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.0.name", "someString"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.0.description", "Some string value"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.0.type", "string"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.0.value.string.value", "some value"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.1.name", "someBoolean"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.1.description", "Some boolean value"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.1.type", "boolean"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.1.value.boolean.value", "true"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "force_delete", "true"),
					resource.TestCheckResourceAttrPair(
						"aria_orchestrator_configuration.test", "category_id",
						"aria_orchestrator_category.root", "id",
					),
				),
			},
			// Update (name) and Read testing
			{
				Config: `
resource "aria_orchestrator_category" "root" {
  name      = "TEST_ARIA_PROVIDER"
  type      = "ConfigurationElementCategory"
  parent_id = ""
}

resource "aria_orchestrator_configuration" "test" {
  name        = "Test Config Renamed"
  description = "Config generated by the acceptance tests of Aria provider (updated)."
  category_id = aria_orchestrator_category.root.id
  version     = "0.1.0"

  attributes = [
    {
      name        = "someString"
      description = "Some string value"
      type        = "string"
      value = {
        string = {
          value = "some value"
        }
      }
    },
    {
      name        = "someBoolean"
      description = "Some boolean value"
      type        = "boolean"
      value = {
        boolean = {
          value = true
        }
      }
    }
  ]

  force_delete = true
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_orchestrator_configuration.test", "id"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "name", "Test Config Renamed"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "description", "Config generated by the acceptance tests of Aria provider (updated)."),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "version", "0.1.0"),
					resource.TestMatchResourceAttr("aria_orchestrator_configuration.test", "version_id", regexp.MustCompile("[0-9a-f]{40}")),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.#", "2"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "force_delete", "true"),
					resource.TestCheckResourceAttrPair(
						"aria_orchestrator_configuration.test", "category_id",
						"aria_orchestrator_category.root", "id",
					),
				),
			},
			// Update (category) and Read testing
			{
				Config: `
resource "aria_orchestrator_category" "root" {
  name      = "TEST_ARIA_PROVIDER"
  type      = "ConfigurationElementCategory"
  parent_id = ""
}

resource "aria_orchestrator_category" "misc" {
  name      = "Misc"
  type      = "ConfigurationElementCategory"
  parent_id = aria_orchestrator_category.root.id
}

resource "aria_orchestrator_configuration" "test" {
  name        = "Test Config Renamed"
  description = "Config generated by the acceptance tests of Aria provider (updated)."
  category_id = aria_orchestrator_category.misc.id
  version     = "0.1.0"

  attributes = [
    {
      name        = "someString"
      description = "Some string value"
      type        = "string"
      value = {
        string = {
          value = "some value"
        }
      }
    },
    {
      name        = "someBoolean"
      description = "Some boolean value"
      type        = "boolean"
      value = {
        boolean = {
          value = true
        }
      }
    }
  ]

  force_delete = true
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_orchestrator_configuration.test", "id"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "name", "Test Config Renamed"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "description", "Config generated by the acceptance tests of Aria provider (updated)."),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "version", "0.1.0"),
					resource.TestMatchResourceAttr("aria_orchestrator_configuration.test", "version_id", regexp.MustCompile("[0-9a-f]{40}")),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "attributes.#", "2"),
					resource.TestCheckResourceAttr("aria_orchestrator_configuration.test", "force_delete", "true"),
					resource.TestCheckResourceAttrPair(
						"aria_orchestrator_configuration.test", "category_id",
						"aria_orchestrator_category.misc", "id",
					),
				),
			},
			// ImportState testing
			{
				ResourceName:      "aria_orchestrator_configuration.test",
				ImportState:       true,
				ImportStateVerify: true,

				// Prevent diff on force_delete field
				ImportStateVerifyIgnore: []string{"force_delete"},
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}
