// Copyright (c) State of Geneva (Switzerland)
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccPropertyGroupResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: `
variable "test_project_id" {
  description = "Project where to generate test resources."
  type        = string
}

resource "aria_property_group" "test" {
  name        = "ARIA_PROVIDER_TEST_PROPERTY_GROUP"
  description = "Temporary property group generated by Aria provider's acceptance tests."
  type        = "INPUT"

  properties = [
    {
      name        = "some_text"
      title       = "Some Text"
      description = "Some text, more text."
      type        = "string"
      one_of      = [
        { const = "a", title = "A", encrypted = false },
        { const = "b", title = "B", encrypted = false }
      ]
    },
    {
      name        = "number"
      title       = "Some Number"
      description = <<EOT
Some number.
It can be an integer or a float.
EOT
      type    = "number"
      default = "3.141592"
      minimum = 0
      maximum = 5
    },
    {
      name        = "super_secret"
      title       = "Super Secret"
      description = ""
      type        = "string"
      # TODO https://github.com/davidfischer-ch/terraform-provider-aria/issues/35
      # encrypted   = true
      min_length  = 16
      max_length  = 64
    },
    {
      name        = "other"
      title       = "Other"
      description = ""
      type        = "string"
    }
  ]
}
`,
				/*Check: TODO,*/
			},
			// Update Templates Test
			/*{
							Config: `

			`,
							// Check: TODO
						},*/
			// ImportState testing
			/*{
			  ResourceName:      "aria_property_group.test",
			  ImportState:       true,
			  ImportStateVerify: true,
			},*/
			// Delete testing automatically occurs in TestCase
			// TODO Check https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests/testcase#checkdestroy
		},
	})
}
