// Copyright (c) State of Geneva (Switzerland)
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccCustomResourceResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: `
variable "test_project_id" {
  description = "Project where to generate test resources."
  type        = string
}

resource "aria_abx_action" "reset" {
  name            = "Custom.AriaProviderTest.reset"
  description     = "Temporary action generated by Aria provider's acceptance tests."
  runtime_name    = "python"
  memory_in_mb    = 128
  timeout_seconds = 60
  entrypoint      = "handler"
  dependencies    = []
  constants       = []
  secrets         = []
  source          = <<EOT
import os

def handler(*args, **kwargs):
    print('Global symbols :', globals())
    print('Environment variables :', os.environ)
    print('Call Arguments: ', args, kwargs)
EOT
  shared          = true
  project_id      = var.test_project_id
}

/*resource "aria_resource_action" "test_reset" {
  name          = "reset_my_stuff"
  display_name  = "Reset My Stuff"
  description   = "Reset my stuff."
  resource_type = aria_custom_resource.test.resource_type
  project_id    = aria_custom_resource.test.project_id
  runnable_item = {
    id                = aria_abx_action.reset.id
    project_id        = aria_abx_action.reset.project_id
    type              = "abx.action"
    input_parameters  = []
    output_parameters = []
  }
}*/
`,
				/*Check: resource.ComposeAggregateTestCheckFunc(
				    resource.TestCheckResourceAttrSet("aria_abx_action.test", "id"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "name", "ARIA_PROVIDER_TEST_ACTION"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "description", "Temporary action generated by Aria provider's acceptance tests."),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "faas_provider", "auto"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "type", "SCRIPT"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "runtime_name", "python"),
				    // resource.TestCheckResourceAttrSet("aria_abx_action.test", "runtime_version"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "cpu_shares", "1024"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "memory_in_mb", "128"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "timeout_seconds", "60"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "deployment_timeout_seconds", "900"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "entrypoint", "handler"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "shared", "true"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "system", "false"),
				    resource.TestCheckResourceAttr("aria_abx_action.test", "async_deployed", "false"),
				    resource.TestCheckResourceAttrSet("aria_abx_action.test", "org_id"),
				),*/
			},
			// Delete testing automatically occurs in TestCase
			// TODO Check https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests/testcase#checkdestroy
		},
	})
}
