// Copyright (c) State of Geneva (Switzerland)
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccResourceActionResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: `
variable "test_project_id" {
  description = "Project where to generate test resources."
  type        = string
}

resource "aria_abx_action" "machine_reset" {
  name            = "ARIA_PROVIDER_MACHINE_RESET"
  description     = "Temporary action generated by Aria provider's acceptance tests."
  runtime_name    = "python"
  memory_in_mb    = 128
  timeout_seconds = 60
  entrypoint      = "handler"
  dependencies    = []
  constants       = []
  secrets         = []
  source          = <<EOT
import os

def handler(*args, **kwargs):
    print('Global symbols :', globals())
    print('Environment variables :', os.environ)
    print('Call Arguments: ', args, kwargs)
EOT
  shared     = true
  project_id = var.test_project_id
}

resource "aria_resource_action" "test" {
  name          = aria_abx_action.machine_reset.name
  display_name  = "Reset"
  description   = "Reset the machine."
  resource_type = "Cloud.vSphere.Machine"
  status        = "DRAFT"
  project_id    = var.test_project_id
  runnable_item = {
    id                = aria_abx_action.machine_reset.id
    project_id        = aria_abx_action.machine_reset.project_id
    type              = "abx.action"
    input_parameters  = []
    output_parameters = []
  }
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "id"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "name", "ARIA_PROVIDER_MACHINE_RESET"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "display_name", "Reset"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "description", "Reset the machine."),
					resource.TestCheckResourceAttr("aria_resource_action.test", "resource_type", "Cloud.vSphere.Machine"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "status", "DRAFT"),
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "project_id"),
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "org_id"),
				),
			},
			// Update testing
			{
				Config: `
variable "test_project_id" {
  description = "Project where to generate test resources."
  type        = string
}

resource "aria_abx_action" "machine_reset" {
  name            = "ARIA_PROVIDER_MACHINE_RESET"
  description     = "Temporary action generated by Aria provider's acceptance tests."
  runtime_name    = "python"
  memory_in_mb    = 128
  timeout_seconds = 60
  entrypoint      = "handler"
  dependencies    = []
  constants       = []
  secrets         = []
  source          = <<EOT
import os

def handler(*args, **kwargs):
    print('Global symbols :', globals())
    print('Environment variables :', os.environ)
    print('Call Arguments :', args, kwargs)
EOT
  shared     = true
  project_id = var.test_project_id
}

resource "aria_resource_action" "test" {
  name          = "${aria_abx_action.machine_reset.name}_RENAMED"
  display_name  = "RESET"
  description   = "Reset the machine..."
  resource_type = "Cloud.vSphere.Machine"
  status        = "RELEASED"
  project_id    = var.test_project_id
  runnable_item = {
    id                = aria_abx_action.machine_reset.id
    project_id        = aria_abx_action.machine_reset.project_id
    type              = "abx.action"
    input_parameters  = []
    output_parameters = []
  }
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "id"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "name", "ARIA_PROVIDER_MACHINE_RESET_RENAMED"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "display_name", "RESET"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "description", "Reset the machine..."),
					resource.TestCheckResourceAttr("aria_resource_action.test", "resource_type", "Cloud.vSphere.Machine"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "status", "RELEASED"),
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "project_id"),
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "org_id"),
				),
			},
			// Delete testing automatically occurs in TestCase
			// TODO Check https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests/testcase#checkdestroy
		},
	})
}
