// Copyright (c) State of Geneva (Switzerland)
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccCatalogSourceForWorkflowResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: `
variable "test_workflow_id" {
  description = "Orchestrator workflow the resource action runs."
  type        = string
}

variable "test_workflow_name" {
  description = "Orchestrator workflow the resource action runs."
  type        = string
}

data "aria_integration" "vro" {
  type_id = "com.vmw.vro.workflow"
}

# Use the workflow as a Day 2 action
resource "aria_resource_action" "test" {
  name          = "AriaProviderTestRA"
  display_name  = "Aria Provider Test Workflow Based RA"
  description   = "Resource action generated by the acceptance tests of Aria provider."
  provider_name = "vro-workflow"
  resource_type = "Deployment"
  status        = "RELEASED"
  project_id    = ""
  runnable_item = {
    id            = var.test_workflow_id
    name          = var.test_workflow_name
    project_id    = ""
    type          = "vro.workflow"
    endpoint_link = data.aria_integration.vro.endpoint_configuration_link
    input_parameters = [
      {
        name        = "deployment"
        description = "TODO"
        type        = "string"
      }
    ]
    output_parameters = []
  }
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(

					// Resource Action - Core
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "id"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "name", "AriaProviderTestRA"),
					resource.TestCheckResourceAttr(
						"aria_resource_action.test", "display_name", "Aria Provider Test Workflow Based RA",
					),
					resource.TestCheckResourceAttr(
						"aria_resource_action.test", "description",
						"Resource action generated by the acceptance tests of Aria provider.",
					),
					resource.TestCheckResourceAttr("aria_resource_action.test", "provider_name", "vro-workflow"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "resource_type", "Deployment"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "status", "RELEASED"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "project_id", ""),
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "org_id"),

					// Resource Action - Form definition generated by the platform
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "form_definition.id"),
					resource.TestCheckResourceAttr(
						"aria_resource_action.test", "form_definition.name", "AriaProviderTestRA",
					),
					resource.TestCheckResourceAttr("aria_resource_action.test", "form_definition.type", "requestForm"),
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "form_definition.form"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "form_definition.form_format", "JSON"),
					resource.TestCheckResourceAttr("aria_resource_action.test", "form_definition.styles", ""),
					resource.TestCheckResourceAttrPair(
						"aria_resource_action.test", "form_definition.source_id",
						"aria_resource_action.test", "id",
					),
					resource.TestCheckResourceAttr(
						"aria_resource_action.test", "form_definition.source_type", "resource.action",
					),
					resource.TestCheckResourceAttrSet("aria_resource_action.test", "form_definition.tenant"),
					resource.TestMatchResourceAttr(
						"aria_resource_action.test", "form_definition.status",
						regexp.MustCompile(`^(ON|OFF)$`),
					),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}
