# Shell script exporting every TF_VAR_test_* variable, source it before make testacc.

resource "local_file" "env" {
  filename        = "${path.module}/env.sh"
  file_permission = "0700"

  content = <<-EOT
    #!/usr/bin/env bash
    # Generated by terraform-provider-aria/tests/setup, do not edit.
    export TF_VAR_test_org_id=${aria_abx_action.test.org_id}
    export TF_VAR_test_project_id=${vra_project.test[0].id}
    export TF_VAR_test_project_ids=${join(",", vra_project.test[*].id)}
    export TF_VAR_test_abx_action_id=${aria_abx_action.test.id}
    export TF_VAR_test_catalog_item_id=${data.aria_catalog_item.test.id}
    export TF_VAR_test_catalog_item_type=${data.aria_catalog_item.test.type_id}
    export TF_VAR_test_icon_id=${aria_icon.test.id}
    export TF_VAR_test_secret_id=${restful_resource.secret.output.id}
    export TF_VAR_test_approver_name=${local.approver_name}
  EOT
}
