# Projects hosting the resources generated by the acceptance tests.
#
# The first one is TF_VAR_test_project_id, the whole set is TF_VAR_test_project_ids.
# Three of them are required, the subscription tests scope a subscription to a list of projects.

resource "vra_project" "test" {
  count = 3

  name             = "${local.prefix}_PROJECT_${count.index + 1}"
  description      = "Project hosting the resources generated by Aria provider's acceptance tests."
  shared_resources = false
}
